spring.application.name=backend
# Tell Spring Boot to use the Cloud Cluster and NOT localhost
spring.mongodb.uri=mongodb+srv://viveksocs_db_user:CnXVN9Sv4S3hex7I@cluster0.ydjqaza.mongodb.net/EcoBinDB?retryWrites=true&w=majority
server.port=8081
server.address=0.0.0.0